doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: admin, password: admin, dbname: pimcore, mapping_types: { enum: string, bit: boolean }, server_version: 8.0.44-0ubuntu0.24.04.2 } } }
